### ISSUE TITLE
Invalid OpenPGP key for v0.9.0

### ISSUE THREAD

**Issue by dmlemos** [krallin/tini#43] opened 2016-07-06 10:15 UTC
**Dockerfile**

```Dockerfile
ENV TINI_VERSION=0.9.0
RUN curl -SL "https://github.com/krallin/tini/releases/download/$v{TINI_VERSION}/tini" -o /tini \
 && curl -SL "https://github.com/krallin/tini/releases/download/$v{TINI_VERSION}/tini.asc" -o /tini.asc \
 && export GNUPGHOME="$(mktemp -d)" \
 && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0527A9B7 \
 && gpg --batch --verify /tini.asc /tini \
 && rm -rf "$GNUPGHOME" /tini.asc \
 && chmod +x /tini
```

**Output**
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21    0    21    0     0     37      0 --:--:-- --:--:-- --:--:--    37
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21    0    21    0     0     36      0 --:--:-- --:--:-- --:--:--    36
gpg: keyring `/tmp/tmp.iBJOxJVo0f/secring.gpg' created
gpg: keyring `/tmp/tmp.iBJOxJVo0f/pubring.gpg' created
gpg: requesting key 0527A9B7 from hkp server ha.pool.sks-keyservers.net
gpg: /tmp/tmp.iBJOxJVo0f/trustdb.gpg: trustdb created
gpg: key 7001A4E5: public key "Thomas Orozco <thomas@orozco.fr>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```

**Comment by krallin** [comment] 2016-07-06 10:23
@dmlemos you're not actually downloading the signature here. If you e.g. run `cat /tini.asc` before attempting to verify it, you'll notice that it's a JSON error payload indicating the file is not found. This error is caused by two issues:

- You're not running curl with the `-f` flag, so it's not failing on a 404
- There's a typo in your URLs. It should be `v${TINI_VERSION}` not `$v{TINI_VERSION}`

Here's a fixed install stanza:

```
ENV TINI_VERSION=0.9.0
RUN curl -fsSL "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini" -o /tini \
 && curl -fsSL "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini.asc" -o /tini.asc \
 && export GNUPGHOME="$(mktemp -d)" \
 && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0527A9B7 \
 && gpg --batch --verify /tini.asc /tini \
 && rm -rf "$GNUPGHOME" /tini.asc \
 && chmod +x /tini
```

**Closed by krallin** 2016-07-06 10:23 UTC

**Comment by dmlemos** [comment] 2016-07-06 10:37
@krallin Thank you for the prompt response. Didn't realise the typo 👍

**Comment by krallin** [comment] 2016-07-06 10:37
Sure; you're welcome! :)
